# preload = ~/.config/hypr/qq.png
# wallpaper = ,~/.config/hypr/qq.png

wallpaper {
    monitor = DVI-D-1
    path = ~/.config/hypr/qq.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/qq.png
    fit_mode = cover
}
